# Generated by Django 5.1.6 on 2025-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='course/')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('star_image', models.FileField(upload_to='course/')),
                ('rating', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
    ]
