# Generated by Django 5.1.6 on 2025-02-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='instructor/')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('star', models.FileField(upload_to='instructor/')),
                ('rate', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
            ],
        ),
    ]
