# Generated by Django 5.1.6 on 2025-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='review/')),
                ('name', models.CharField(max_length=255)),
                ('star', models.FileField(upload_to='review/')),
                ('rating', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
