# Generated by Django 5.1.6 on 2025-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
