# Generated by Django 5.1.6 on 2025-02-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_course_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category_name',
        ),
    ]
