# Generated by Django 5.1.6 on 2025-02-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_course_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='design/')),
                ('discounted_price', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
            ],
        ),
    ]
