# Generated by Django 5.1.6 on 2025-02-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='discounted_price',
        ),
    ]
