# Generated by Django 5.1.6 on 2025-02-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_design_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
