# Generated by Django 5.1.6 on 2025-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_design_discount_alter_design_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='discount',
            field=models.CharField(max_length=255),
        ),
    ]
